### ISSUE TITLE
As a content creator, I want to include a Facebook(Meta) Pixel for user engangement insights and tracking.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#51]
As a content creator, I want to include a Facebook(Meta) Pixel for user engangement insights and tracking.

You can find a simple guide from Vercel on how to fully integrate the Meta Pixel within Next.js for event and page handling.

From my initial research, the "fb:app_id" rich snippet data point that is included in the Next-Seo component is no longer used by Facebook. This .env var and Next-SEO code should be removed.

- [ ] Delete reference to NEXT_PUBLIC_FACEBOOK_APP_ID in .env.example file
- [ ] Delete process.env.NEXT_PUBLIC_FACEBOOK_APP_ID code within Elegant.
- [ ] Remove Config('app.fb') from line 168 of source\elegant\src\pages\_app.js
- [ ] Add the pixel .env var as mentioned in the guide.
- [ ] Add the complete pixel functionality as mentioned in the guide.
